### ISSUE TITLE
eth_getTransactionReceipt returns null for all transactions in some blocks

### ISSUE THREAD

**Issue by zimbabao** [celo-org/celo-blockchain#2014]
## Description
Fully synced archive node returns null as a response to eth_getTransactionReceipt for all transactions for some blocks.
This is unexpected, the chain continues to sync fine.  

## Current Behavior
For this block https://celoscan.io/block/10158797 (and may be more)
I get following response 
```
curl  http://localhost:8545   -X POST  -H "Content-Type: application/json"  --data '{"method":"eth_getTransactionReceipt","params":["0xd426b6bbd686e2588ea8bb20612ba3e78ab37f3b0dc70b955241677832aab4a9"],"id":1,"jsonrpc":"2.0"}'
{"jsonrpc":"2.0","id":1,"result":null}
```

Config
```
          image: us.gcr.io/celo-org/geth:mainnet
          imagePullPolicy: Always
          args:
            - --syncmode=full
            - --datadir=/root/.celo/
            - --datadir.ancient=/root/.celo/celo/chaindata/ancient
            - --http
            - --http.addr=0.0.0.0
            - --http.api=eth,net,web3,txpool,admin,debug
            - --ws
            - --ws.addr=0.0.0.0
            - --ws.api=eth,net,web3,txpool,admin,debug
            - --metrics
            - --metrics.addr=0.0.0.0
            - --txlookuplimit=0
            - --gcmode=archive
            - --light.serve=90
            - --light.maxpeers=90
            - --maxpeers=300
            - --rpc.gascap=300000000 # 300M limit on gas, default is 50M
            - --http.vhosts=*
            - --cache=200000
            - --cache.preimages
            - --verbosity=3
  ```
## Context
Node is synced from genesis. A couple of time disk got full and I increased the disk size and restarted the node.
